# Generated by Django 5.2 on 2025-07-04 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_url', models.URLField(db_index=True, max_length=500)),
                ('poster_url', models.URLField(blank=True, max_length=500, null=True)),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('poster_image_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('video_url', models.URLField(db_index=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('video_file_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='phrase.movie')),
            ],
        ),
    ]
